# Generated by Django 3.1.1 on 2020-10-07 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='profiles/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.profile')),
            ],
        ),
    ]
